# Generated by Django 6.0.2 on 2026-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("firstname", models.CharField(blank=True, max_length=100, null=True)),
                ("middlename", models.CharField(blank=True, max_length=100, null=True)),
                ("lastname", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("group_id", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tbl_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "particular",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "tbl_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                ("entry_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("hh_id", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hh_set", models.CharField(blank=True, max_length=50, null=True)),
                ("prog", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "relation_to_hh_head",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("grantee", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "member_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": '"ds"."tbl_roster"',
                "managed": False,
            },
        ),
    ]
