# Generated by Django 6.0.2 on 2026-03-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finder_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
        migrations.AlterModelTable(
            name='user',
            table='"public"."tbl_users"',
        ),
    ]
